version: "3"

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  pong:
    build: ./pong
    container_name: pong
    volumes:
      - staticfiles:/pong/staticfiles
      - media:/pong/media
      - ssl:/etc/nginx/ssl
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - staticfiles:/pong/staticfiles
      - media:/pong/media
      - ssl:/etc/nginx/ssl
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - pong
    networks:
      - mynetwork

volumes:
  postgres_data:
  staticfiles:
  media:
  ssl:
  
networks:
  mynetwork:
    driver: bridge
