# Generated by Django 5.1 on 2024-12-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mp',
            field=models.IntegerField(default=0, verbose_name='Matrix Point'),
        ),
    ]
